// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_middleware from "./routes/_middleware.ts";
import * as $api_credits from "./routes/api/credits.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logo from "./routes/api/logo.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_music from "./routes/api/music.ts";
import * as $api_photo_data from "./routes/api/photo_data.ts";
import * as $api_photos from "./routes/api/photos.ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/credits.ts": $api_credits,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logo.ts": $api_logo,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/music.ts": $api_music,
    "./routes/api/photo_data.ts": $api_photo_data,
    "./routes/api/photos.ts": $api_photos,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
