// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_credits from "./routes/api/credits.ts";
import * as $api_logo from "./routes/api/logo.ts";
import * as $api_music from "./routes/api/music.ts";
import * as $api_photo_data from "./routes/api/photo_data.ts";
import * as $api_photos from "./routes/api/photos.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $AdminDashboard from "./islands/AdminDashboard.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/credits.ts": $api_credits,
    "./routes/api/logo.ts": $api_logo,
    "./routes/api/music.ts": $api_music,
    "./routes/api/photo_data.ts": $api_photo_data,
    "./routes/api/photos.ts": $api_photos,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
  },
  islands: {
    "./islands/AdminDashboard.tsx": $AdminDashboard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
